# Home task 01: Python basics Julia Mendoza Verduzco
"""create list of 100 random numbers from 0 to 1000
sort list from min to max (without using sort())
calculate average for even and odd numbers
print both average result in console
Each line of code should be commented with description.
Commit script to git repository and provide link as home task result. """

import random

list_of_numbers = []

# create list of 100 random numbers from 0 to 1000
def create_list_of_numbers():
    for i in range(100):  # loop of 100 to generate the numbers
        random_numbers = random.randint(0, 1000)  # random functions to get the numbers
        list_of_numbers.append(random_numbers)  # adding the random numbers to the list
       # print(random_numbers)
    return list_of_numbers #retuning the list to be used in the next step

#sort the list from min to max (without using sort())
def selection_sort(list_of_numbers):
    for i in range(len(list_of_numbers)):  # loop to iterate through the length of the list
        min_index = i  #setting  as the minimum element
        for j in range(i + 1, len(list_of_numbers)):  # loop to iterate the length of the list
            if list_of_numbers[min_index] > list_of_numbers[j]:  # checking if the current value is greater than the one in the next position
                min_index = j  # if it's then setting the index to the next position
        list_of_numbers[i], list_of_numbers[min_index] = list_of_numbers[min_index], list_of_numbers[i]  # swapping the values to leave the minor in the previous position and index has been updated
    return list_of_numbers  # returning the sorted list

#calculate average for even and odd numbers
def average_even_odd(list_for_average):
    even_sum = 0 #sum of even numbers
    odd_sum = 0 #sum of odd numbers
    even_count = 0 #count of even numbers
    odd_count = 0 #count of odd numbers
    for i in list_for_average: #for each element in the list -already sorted-
        if i % 2 == 0: #if not residue of module operation then is even
            even_sum += i #adding to the sum of even numbers
            even_count += 1 #incrementing the count of even numbers
        else: #if there is a residue when dividing by 2
            odd_sum += i #adding to the sum of odd numbers
            odd_count += 1 #incrementing the count of odd numbers
    return (even_sum / even_count, #sum of all the even divided by their count
            odd_sum / odd_count) #sum of all the odd divided by their count and returning both values

list_for_average = selection_sort(create_list_of_numbers())  # list sorted generated by create list of numbers and sorted by selection sort
print("Average for even and odd numbers: ",average_even_odd(list_for_average))


